/** -- updated 2024-05-09 --
 * Project: Midi2
 * File:    MidiDefs.h
 * Author:  Mike Liddle
 * Created: 2024-05-09
 * License: MIT
 *
 * Copyright (c) 2024 Mike Liddle
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy 
 * of this software and associated documentation files (the "Software"), to deal 
 * in the Software without restriction, including without limitation the rights 
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
 * copies of the Software, and to permit persons to whom the Software is 
 * furnished to do so, subject to the following conditions: 
 *  
 * The above copyright notice and this permission notice shall be included in all 
 * copies or substantial portions of the Software. 
 *  
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * Mike LiddleS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 * SOFTWARE.
 **/
#ifndef _MIDI_DEFS_H_
#define _MIDI_DEFS_H_

// MESSAGE TYPES
#define MIDI_NOTE_OFF 0x80
#define MIDI_NOTE_ON 0x90
#define MIDI_POLYPHONIC_AFTERTOUCH 0xA0
#define MIDI_CONTROL_CHANGE 0xB0
#define MIDI_PROGRAM_CHANGE 0xC0
#define MIDI_CHANNEL_AFTERTOUCH 0xD0
#define MIDI_PITCH_BEND 0xE0
#define MIDI_SYSTEM 0xF0

// CLOCK MESSAGES
#define MIDI_CLOCK_TICK 0xF8  // 1111 1000
#define MIDI_CLOCK_START 0xFA  // 1111 1010
#define MIDI_CLOCK_CONTINUE 0xFB  // 1111 1011
#define MIDI_CLOCK_STOP 0xFC  // 1111 1100
#define MIDI_CLOCK_SENSE 0xFE  // 1111 1110
#define MIDI_CLOCK_RESET 0xFF  // 1111 1111
#define MIDI_CLOCK_TYPE MIDI_CLOCK_TICK

// SYSTEM MESSAGES
#define MIDI_SYSTEM_SYSEX_START 0xF0
#define MIDI_SYSTEM_SONG_POSITION_POINTER 0xF2
#define MIDI_SYSTEM_SONG_SELECT 0xF3
#define MIDI_SYSTEM_TUNE_REQUEST 0xF6
#define MIDI_SYSTEM_END_OF_EXCLUSIVE 0xF7

// CONTROL MESSAGES
#pragma region CONTROL_CHANGE_MESSAGES
// more details here: https://anotherproducer.com/online-tools-for-musicians/midi-cc-list/
#define MIDI_BANK_SELECT 0x00
#define MIDI_MODULATION_WHEEL 0x01
#define MIDI_BREATH_CONTROLLER 0x02
#define MIDI_FOOT_CONTROLLER 0x04
#define MIDI_PORTAMENTO_TIME 0x05
#define MIDI_DATA_ENTRY 0x06
#define MIDI_CHANNEL_VOLUME 0x07
#define MIDI_BALANCE 0x08
#define MIDI_PAN 0x0A
#define MIDI_EXPRESSION_CONTROLLER 0x0B
#define MIDI_EFFECT_CONTROL_1 0x0C
#define MIDI_EFFECT_CONTROL_2 0x0D
#define MIDI_GENERAL_PURPOSE_CONTROLLER_1 0x10
#define MIDI_GENERAL_PURPOSE_CONTROLLER_2 0x11
#define MIDI_GENERAL_PURPOSE_CONTROLLER_3 0x12
#define MIDI_GENERAL_PURPOSE_CONTROLLER_4 0x13
#define MIDI_BANK_SELECT_LSB 0x20
#define MIDI_MODULATION_WHEEL_LSB 0x21
#define MIDI_BREATH_CONTROLLER_LSB 0x22
#define MIDI_FOOT_CONTROLLER_LSB 0x24
#define MIDI_PORTAMENTO_TIME_LSB 0x25
#define MIDI_DATA_ENTRY_LSB 0x26
#define MIDI_CHANNEL_VOLUME_LSB 0x27
#define MIDI_BALANCE_LSB 0x28
#define MIDI_PAN_LSB 0x2A
#define MIDI_EXPRESSION_CONTROLLER_LSB 0x2B
#define MIDI_EFFECT_CONTROL_1_LSB 0x2C
#define MIDI_EFFECT_CONTROL_2_LSB 0x2D
#define MIDI_GENERAL_PURPOSE_CONTROLLER_1_LSB 0x30
#define MIDI_GENERAL_PURPOSE_CONTROLLER_2_LSB 0x31
#define MIDI_GENERAL_PURPOSE_CONTROLLER_3_LSB 0x32
#define MIDI_GENERAL_PURPOSE_CONTROLLER_4_LSB 0x33
#define MIDI_SUSTAIN_PEDAL 0x40
#define MIDI_PORTAMENTO 0x41
#define MIDI_SOSTENUTO 0x42
#define MIDI_SOFT_PEDAL 0x43
#define MIDI_LEGATO_FOOTSWITCH 0x44
#define MIDI_HOLD_2 0x45
#define MIDI_SOUND_CONTROLLER_1 0x46
#define MIDI_SOUND_CONTROLLER_2 0x47
#define MIDI_SOUND_CONTROLLER_3 0x48
#define MIDI_SOUND_CONTROLLER_4 0x49
#define MIDI_SOUND_CONTROLLER_5 0x4A
#define MIDI_SOUND_CONTROLLER_6 0x4B
#define MIDI_SOUND_CONTROLLER_7 0x4C
#define MIDI_SOUND_CONTROLLER_8 0x4D
#define MIDI_SOUND_CONTROLLER_9 0x4E
#define MIDI_SOUND_CONTROLLER_10 0x4F
#define MIDI_GENERAL_PURPOSE_CONTROLLER_5 0x50
#define MIDI_GENERAL_PURPOSE_CONTROLLER_6 0x51
#define MIDI_GENERAL_PURPOSE_CONTROLLER_7 0x52
#define MIDI_GENERAL_PURPOSE_CONTROLLER_8 0x53
#define MIDI_PORTAMENTO_CONTROL 0x54
#define MIDI_EFFECTS_1 0x5B
#define MIDI_EFFECTS_2 0x5C
#define MIDI_EFFECTS_3 0x5D
#define MIDI_EFFECTS_4 0x5E
#define MIDI_EFFECTS_5 0x5F
#define MIDI_DATA_INCREMENT 0x60
#define MIDI_DATA_DECREMENT 0x61
#define MIDI_NON_REGISTERED_PARAMETER_NUMBER_LSB 0x62
#define MIDI_NON_REGISTERED_PARAMETER_NUMBER_MSB 0x63
#define MIDI_REGISTERED_PARAMETER_NUMBER_LSB 0x64
#define MIDI_REGISTERED_PARAMETER_NUMBER_MSB 0x65
#define MIDI_ALL_SOUND_OFF 0x78
#define MIDI_RESET_ALL_CONTROLLERS 0x79
#define MIDI_LOCAL_CONTROL 0x7A
#define MIDI_ALL_NOTES_OFF 0x7B
#define MIDI_OMNI_MODE_OFF 0x7C
#define MIDI_OMNI_MODE_ON 0x7D
#define MIDI_MONO_MODE_ON 0x7E
#define MIDI_POLY_MODE_ON 0x7F
#pragma endregion CONTROL_MESSAGES

#define MIDI_DATA_BYTE 0x7F  // 0111 1111 Mask for 7 bits.

// HELPER MACROS
#define MIDI_DECODE_DATA(byte) (byte & MIDI_DATA_BYTE)
#define MIDI_DECODE_TYPE(byte) (byte & 0xF0 )
#define MIDI_DECODE_CHANNEL(byte) (byte & 0x0F)
#define MIDI_IS_SYSTEM_MESSAGE(byte) (byte & MIDI_SYSTEM)
#define MIDI_CAN_USE_RUNNING_STATUS(byte) !MIDI_IS_SYSTEM_MESSAGE(byte)

#pragma region CHANNELS

// MIDI CHANNELS
#define MIDI_CHANNEL_1    1
#define MIDI_CHANNEL_2    2
#define MIDI_CHANNEL_3    3
#define MIDI_CHANNEL_4    4
#define MIDI_CHANNEL_5    5
#define MIDI_CHANNEL_6    6
#define MIDI_CHANNEL_7    7
#define MIDI_CHANNEL_8    8
#define MIDI_CHANNEL_9    9
#define MIDI_CHANNEL_10   10
#define MIDI_CHANNEL_11   11
#define MIDI_CHANNEL_12   12
#define MIDI_CHANNEL_13   13
#define MIDI_CHANNEL_14   14
#define MIDI_CHANNEL_15   15
#define MIDI_CHANNEL_16   16

#pragma endregion CHANNELS

#endif  // _MIDI_DEFS_H_
